use_frameworks!

platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'


target 'LvHttpManager_Example' do
  pod 'LvHttpManager', :path => '../'

  target 'LvHttpManager_Tests' do
    inherit! :search_paths

    
  end
end
